### ISSUE TITLE
Non-MFA login broken

### ISSUE THREAD

**Issue by andig** [uhthomas/tesla#2]
Somehow this has escaped my testing. The non-MFA login must not follow the redirect to `/void/callback` or it cannot read the code from the redirect response. This needs be added to `auth.go`:

	// handle non-MFA case
	a.Client.CheckRedirect = func(req *http.Request, via []*http.Request) error {
		if req.URL.Path == "/void/callback" {
			return http.ErrUseLastResponse
		}
		return nil
	}

Could you kindly double-check that MFA still works after this change?

**Comment by uhthomas** [comment]
That's odd. I'll do some testing tonight, thanks for raising.

**Comment by andig** [comment]
It makes sense. When you `switch` on return code in https://github.com/uhthomas/tesla/blob/master/auth.go#L65 you will never see a HTTP redirect if those have been followed before.

Code above needs to go before or after https://github.com/uhthomas/tesla/blob/master/auth.go#L51.
