### ISSUE TITLE
Failing to login with cmd/login

### ISSUE THREAD

**Issue by bogosj** [uhthomas/tesla#3]
I'm interested in using this library for my project, so I'm trying out the basics and stumbling.

```
cd cmd/login
go build main.go
./main

Username: <redacted>
Password:
2021/02/10 16:05:32 list devices: do: Get "https://auth.tesla.com/oauth2/v3/authorize/mfa/factors?transaction_id=<redacted>": net/http: timeout awaiting response headers
```

Is the idea that for MFA you'd use cmd/login to acquire a token, then that token could be used for all future auth attempts?

**Comment by uhthomas** [comment]
Thanks for your interest in the project!

I assume you don't have MFA enabled on your Tesla account, and so it would be the same as #2. I've raised a PR, #4, which will fix this problem. The tool will spit out two JSON objects, one containing the OAuth2 config, and another containing the OAuth2 Token (access, refresh and expiry).

I hacked together a quick project late last week which uses these and it works well. See [uthomas/tesladump](https://github.com/uhthomas/tesladump/blob/e66e6567554e10145f7293cef43b074c3975402a/internal/oauth2.go#L13-L23) for an example.

**Comment by bogosj** [comment]
I do have MFA enabled on this account.

**Comment by uhthomas** [comment]
That's odd. I tested both flows just a moment ago and got credentials back almost instantly. Would you mind pulling these changes and trying again? Would be interested to see the result.

**Comment by bogosj** [comment]
It's not odd... it's "user error". Apparently in my attempts to get the API working using Go, Ruby, and JS I managed to lock my account out but there was no indication from the API that was the case. Only when I opened an incognito window to ensure I did have MFA on was I told :)

I now have a JSON of `access_token` and `refresh_token`. What would be the next steps to utilize those? Are either of those long-lived?

**Comment by uhthomas** [comment]
Hah, bless you. Glad you got it figured out!

The access token only seems the last 15 minutes, but the refresh token seems to last for weeks, or months (not sure).

The two JSON objects are the exact representation of Go's [OAuth2 Config](https://pkg.go.dev/golang.org/x/oauth2#Config) and [OAuth2 Token](https://pkg.go.dev/golang.org/x/oauth2#Token). They can be used together to create an OAuth2 HTTP client using the config's [Client](https://pkg.go.dev/golang.org/x/oauth2#Config.Client) func. Refer to [this example](https://github.com/uhthomas/tesladump/blob/e66e6567554e10145f7293cef43b074c3975402a/internal/oauth2.go#L13-L23) for how that looks all together.

That should be it - let me know how you get on.
