### ISSUE TITLE
OAuth2 authorization timeout

### ISSUE THREAD

**Issue by uhthomas** [uhthomas/tesla#5]
Not really sure what could be causing this. I can login find in browser.
```
2021/02/25 22:21:01 login: Post "https://auth.tesla.com/oauth2/v3/authorize?access_type=offline&client_id=ownerapi&code_challenge=<redacted>&code_challenge_method=S256&redirect_uri=https%3A%2F%2Fauth.tesla.com%2Fvoid%2Fcallback&response_type=code&scope=openid+email+offline_access&state=": net/http: timeout awaiting response headers
```

**Comment by uhthomas** [comment]
Looks maybe related? https://github.com/timdorr/tesla-api/issues/321

It was closed, but removing the User-Agent header doesn't seem to be very fruitful.

**Comment by uhthomas** [comment]
Looks like my home IP has somehow got caught in a mass blocklist. Closing.

**Comment by uhthomas** [comment]
Actually, I've just tested on a new network and it looks like something weird is going on.
```
<HTML><HEAD>
<TITLE>Access Denied</TITLE>
</HEAD><BODY>
<H1>Access Denied</H1>

You don't have permission to access "http&#58;&#47;&#47;auth&#46;tesla&#46;com&#47;oauth2&#47;v3&#47;authorize&#63;" on this server.<P>
Reference&#32;&#35;18&#46;cf921602&#46;1614295565&#46;5686a4b
</BODY>
</HTML>
2021/02/25 23:26:03 login: unexpected status code 403
```

I don't know if they switched to AkamaiGHost recently or something but it's just broken everything. This sucks.

**Comment by stx** [comment]
New WAF configuration was deployed at 2pm PST. Not sure what the new rules are.

**Comment by uhthomas** [comment]
Thanks for the info @stx. Not really sure where to start with debugging this.

**Comment by uhthomas** [comment]
This is now fixed. Tesla has updated their WAF settings again.
