### ISSUE TITLE
Login step fails

### ISSUE THREAD

**Issue by andig** [uhthomas/tesla#6]
I have a non-MFA user failing at the login step with current commit at

    GET /oauth2/v3/authorize?access_type=offline&client_id=ownerapi&code_challenge...

response is

    HTTP/2.0 403 Forbidden
    Content-Length: 296
    Content-Type: text/html
    Date: Mon, 01 Mar 2021 17:07:08 GMT
    Expires: Mon, 01 Mar 2021 17:07:08 GMT
    Mime-Version: 1.0
    Server: AkamaiGHost

    <HTML><HEAD>
    <TITLE>Access Denied</TITLE>
    </HEAD><BODY>
    <H1>Access Denied</H1>

    You don't have permission to access "http&#58;&#47;&#47;auth&#46;tesla&#46;com&#47;oauth2&#47;v3&#47;authorize&#63;" on this server.<P>

Check u/p and they are correct. Any idea what might be wrong?

**Comment by uhthomas** [comment]
I imagine this is a repeat of https://github.com/uhthomas/tesla/issues/5#issuecomment-786301273

**Comment by andig** [comment]
Yeah. I got the empty user agent update, but latest seems to have hackney there. Need to find a good approach for https://github.com/bogosj/tesla/issues/22 to not keep reinventing the wheel...
